version: "3.9"

networks:
  transferNet:
    driver: bridge

services:
  postgresServerDb:
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "5022:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /data/transfer/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bober -d mybober"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transferNet
    
  api:
    build: ./WebApiTransfer
    container_name: transfer_api
    volumes:
      - /data/transfer/images:/app/images
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgresServerDb;Database=mydb;Port=5022;Username=ivan;Password=marko123halosh
    ports:
      - "5898:8080"
    depends_on:
      postgresServerDb:
        condition: service_healthy
    networks:
      - transferNet

  front:
    build: 
      context: ./my-transfer-ts
    container_name: react_front
    ports:
      - "3987:80"